Added support for specifying minimum skip length
dmunozv04/iSponsorBlockTV pull request #169
Opened 2024-06-10 03:30 UTC by bourkemcrobbo

Fixes #145 

This provides support to specify minimum segment length to skip

I have no chance of updating the graphical configurator and having it work correctly, I hope the utility provided in the rest of this pull request makes up for it

2024-06-26 18:36 UTC, ryankupk requested changes
I was going to implement this but I'm glad that you beat me to it. Just leaving a couple of notes from things that I discovered while looking into it and to point out the changes to config_setup.py from my PR that will be needed.

2024-06-26 18:47 UTC, dmunozv04 commented on src/iSponsorBlockTV/config_setup.py
> +
Yep, #150 was merged after raising this PR, but refactoring this section of the cli configurator shouldn't be too much work, and ideally a new "panel" would be added to the tui config editor to allow changing this value from there too. I'll be able to do it at some point but if someone wants to go ahead and help you're free to do it. PRs are always appreciated. Thanks for your comment @ryankupk

2024-11-02 11:15 UTC, SimoMay approved these changes

2024-12-16 17:02 UTC, SuperManifolds commented
What's the status on this? It seems to be approved but was never merged?

2025-03-02 23:27 UTC, sternma commented
@dmunozv04 , is there anything left for this MR?  If so, I would be happy to complete any outstanding work so that this feature can get pulled in.

2025-03-12 04:51 UTC, bourkemcrobbo commented
@sternma I was never able to get the graphical configuration utility to populate the minimum skip length value. That would help complete this functionality

2025-03-14 23:12 UTC, sternma commented
Finished in #278.  Thanks @bourkemcrobbo, I made sure to keep your commits in.

2025-04-12 13:07 UTC, dmunozv04 commented
Superseded by #278

2025-04-12 13:07 UTC, closed without merging